# .github/workflows/archives.yml
name: Archives TWC Plugins and Themes

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Run Legacy Scripts
        run: |
          docker run --rm \
            --workdir /github/workspace \
            -v "${{ github.workspace }}:/github/workspace" \
            -e GITHUB_REPOSITORY=${{ github.repository }} \
            -e VERSION=0.1 \
            ubuntu:16.04 bash -c "
              set -e

              # --- STAGE 1: Install Dependencies (as root) ---
              apt-get update && \
              apt-get install -y --no-install-recommends \
                wget \
                git \
                jq \
                software-properties-common \
                build-essential
              apt-add-repository ppa:brightbox/ruby-ng && \
              apt-get update && \
              apt-get install -y --no-install-recommends \
                ruby1.8 \
                ruby1.8-dev && \
              apt-get clean && \
              rm -rf /var/lib/apt/lists/*
              
              # --- STAGE 2: Execute Legacy Script as a non-root user ---
              addgroup --gid $(id -g) runnergroup
              adduser --uid $(id -u) --ingroup runnergroup --disabled-password --gecos '' runner
              
              su runner -c \"
                set -e
                
                if [ ! -d \\\"cooker\\\" ]; then
                    git clone https://github.com/TiddlyWiki/cooker.git
                fi

                mkdir -p split_file
                mkdir -p commit/plugins
                mkdir -p commit/themes

                master_json_output=\\\"[]\\\"
                
                while read url; do
                  if [ -z \\\"\\\$url\\\" ]; then
                    continue
                  fi
                  sanitized_url=\\\$(echo \\\"\\\$url\\\" | sed -E 's/^https?:\/\///' | sed 's/[^a-zA-Z0-9]/_/g')

                  output_html=\\\"\\\${sanitized_url}.html\\\"
                  echo \\\"Processing URL: \\\$url\\\"
                  wget --no-check-certificate -O \\\"\\\${output_html}\\\" \\\"\\\$url\\\"
                  
                  ( cd cooker && ruby ginsu.rb \\\"../\\\${output_html}\\\" -s -d \\\"../split_file\\\" -c UTF-8 )
                  
                  plugins_dir=\\\"split_file/\\\${sanitized_url}.html.0/plugins\\\"
                  if [ -d \\\"\\\$plugins_dir\\\" ]; then
                    echo \\\"Plugins directory exists, copying and generating JSON...\\\"
                    mkdir -p \\\"commit/plugins/\\\${sanitized_url}\\\"
                    cp -r \\\"\\\$plugins_dir\\\"/* \\\"commit/plugins/\\\${sanitized_url}\\\"
                    plugins_json_output=\\\"[]\\\"
                    while read -r line; do
                      # --- FIX #1: Skip blank lines to prevent all other errors. ---
                      if [ -z \\\"\\\$line\\\" ]; then
                        continue
                      fi
                      
                      # --- FIX #2: Use the correct sed command for your 'tiddler: name' format. ---
                      filename=\\\$(echo \\\"\\\$line\\\" | sed -E 's/^tiddler: (.*)\$/\1/')
                      
                      # --- FIX #3: Aggressively find the description in the file. ---
                      description_line=\\\$(grep -i -m 1 'description' \\\"\\\${plugins_dir}/\\\${filename}\\\" || echo \\\"\\\")
                      description=\\\$(echo \\\"\\\$description_line\\\" | sed -E 's/^.*description[[:space:]]*[|:][[:space:]]*//I; s/\|//g')
                      
                      # --- Clean up and apply fallback ---
                      description=\\\$(echo \\\"\\\$description\\\" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//' -e 's/<[^>]*>//g')
                      if [ -z \\\"\\\$description\\\" ]; then
                        description=\\\"\$filename\\\"
                      fi

                      full_url=\\\"https://github.com/\\\${GITHUB_REPOSITORY}/blob/twcArchives/commit/plugins/\\\${sanitized_url}/\\\${filename}\\\"
                      plugins_json_output=\\\$(echo \\\"\\\$plugins_json_output\\\" | jq --arg url \\\"\\\$full_url\\\" --arg desc \\\"\\\$description\\\" '. += [{url: \\\$url, description: \\\$desc}]')
                    done < \\\"\\\${plugins_dir}/split.recipe\\\"
                    json_file_url=\\\"https://github.com/\\\${GITHUB_REPOSITORY}/blob/twcArchives/commit/plugins/\\\${sanitized_url}/\\\${sanitized_url}.txt\\\"
                    echo \\\"|Source|\\\${json_file_url}|\\\" > \\\"commit/plugins/\\\${sanitized_url}/\\\${sanitized_url}.txt\\\"
                    echo \\\"|Version|\\\${VERSION}|\\\" >> \\\"commit/plugins/\\\${sanitized_url}/\\\${sanitized_url}.txt\\\"
                    echo \\\"//{{{\\\" >> \\\"commit/plugins/\\\${sanitized_url}/\\\${sanitized_url}.txt\\\"
                    echo \\\"\\\$plugins_json_output\\\" >> \\\"commit/plugins/\\\${sanitized_url}/\\\${sanitized_url}.txt\\\"
                    echo \\\"//}}}\\\" >> \\\"commit/plugins/\\\${sanitized_url}/\\\${sanitized_url}.txt\\\"
                    master_json_url=\\\"https://github.com/\\\${GITHUB_REPOSITORY}/blob/twcArchives/commit/plugins/\\\${sanitized_url}/\\\${sanitized_url}.txt\\\"
                    master_json_output=\\\$(echo \\\"\\\$master_json_output\\\" | jq --arg url \\\"\\\$master_json_url\\\" --arg desc \\\"\\\$sanitized_url\\\" '. += [{url: \\\$url, description: \\\$desc, type: \\\"collection\\\"}]')
                  else
                    echo \\\"Plugins directory does not exist, skipping.\\\"
                  fi
                  themes_dir=\\\"split_file/\\\${sanitized_url}.html.0/themes\\\"
                  if [ -d \\\"\\\$themes_dir\\\" ]; then
                    echo \\\"Themes directory exists, copying and generating JSON...\\\"
                    mkdir -p \\\"commit/themes/\\\${sanitized_url}\\\"
                    cp -r \\\"\\\$themes_dir\\\"/* \\\"commit/themes/\\\${sanitized_url}\\\"
                    themes_json_output=\\\"[]\\\"
                    while read -r line; do
                      # --- FIX #1: Skip blank lines to prevent all other errors. ---
                      if [ -z \\\"\\\$line\\\" ]; then
                        continue
                      fi

                      # --- FIX #2: Use the correct sed command for your 'tiddler: name' format. ---
                      filename=\\\$(echo \\\"\\\$line\\\" | sed -E 's/^tiddler: (.*)\$/\1/')

                      # --- FIX #3: Aggressively find the description in the file. ---
                      description_line=\\\$(grep -i -m 1 'description' \\\"\\\${themes_dir}/\\\${filename}\\\" || echo \\\"\\\")
                      description=\\\$(echo \\\"\\\$description_line\\\" | sed -E 's/^.*description[[:space:]]*[|:][[:space:]]*//I; s/\|//g')

                      # --- Clean up and apply fallback ---
                      description=\\\$(echo \\\"\\\$description\\\" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*\$//' -e 's/<[^>]*>//g')
                      if [ -z \\\"\\\$description\\\" ]; then
                        description=\\\"\$filename\\\"
                      fi

                      full_url=\\\"https://github.com/\\\${GITHUB_REPOSITORY}/blob/twcArchives/commit/themes/\\\${sanitized_url}/\\\${filename}\\\"
                      themes_json_output=\\\$(echo \\\"\\\$themes_json_output\\\" | jq --arg url \\\"\\\$full_url\\\" --arg desc \\\"\\\$description\\\" '. += [{url: \\\$url, description: \\\$desc}]')
                    done < \\\"\\\${themes_dir}/split.recipe\\\"
                    json_file_url=\\\"https://github.com/\\\${GITHUB_REPOSITORY}/blob/twcArchives/commit/themes/\\\${sanitized_url}/\\\${sanitized_url}.txt\\\"
                    echo \\\"|Source|\\\${json_file_url}|\\\" > \\\"commit/themes/\\\${sanitized_url}/\\\${sanitized_url}.txt\\\"
                    echo \\\"|Version|\\\${VERSION}|\\\" >> \\\"commit/themes/\\\${sanitized_url}/\\\${sanitized_url}.txt\\\"
                    echo \\\"//{{{\\\" >> \\\"commit/themes/\\\${sanitized_url}/\\\${sanitized_url}.txt\\\"
                    echo \\\"\\\$themes_json_output\\\" >> \\\"commit/themes/\\\${sanitized_url}/\\\${sanitized_url}.txt\\\"
                    echo \\\"//}}}\\\" >> \\\"commit/themes/\\\${sanitized_url}/\\\${sanitized_url}.txt\\\"
                    master_json_url=\\\"https://github.com/\\\${GITHUB_REPOSITORY}/blob/twcArchives/commit/themes/\\\${sanitized_url}/\\\${sanitized_url}.txt\\\"
                    master_json_output=\\\$(echo \\\"\\\$master_json_output\\\" | jq --arg url \\\"\\\$master_json_url\\\" --arg desc \\\"\\\$sanitized_url\\\" '. += [{url: \\\$url, description: \\\$desc, type: \\\"collection\\\"}]')
                  else
                    echo \\\"Themes directory does not exist, skipping.\\\"
                  fi
                  rm -rf split_file/*
                  # --- ADDED: Wait for a while before the next URL ---
                  echo \\\"Waiting for 30 seconds...\\\"
                  sleep 30
                done < systemServer.txt
                master_file_url=\\\"https://github.com/\\\${GITHUB_REPOSITORY}/blob/twcArchives/commit/twcArchives.txt\\\"
                echo \\\"|Source|\\\${master_file_url}|\\\" > \\\"commit/twcArchives.txt\\\"
                echo \\\"|Version|\\\${VERSION}|\\\" >> \\\"commit/twcArchives.txt\\\"
                echo \\\"//{{{\\\" >> \\\"commit/twcArchives.txt\\\"
                echo \\\"\\\$master_json_output\\\" >> \\\"commit/twcArchives.txt\\\"
                echo \\\"//}}}\\\" >> \\\"commit/twcArchives.txt\\\"
              \"
            "
      
      - name: Commit and push to twcArchives branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Use a very specific file pattern to avoid committing unwanted files.
          # The '**' is a glob pattern that matches all files inside the directories.
          file_pattern: |
            commit/**
          commit_message: 'Add processed files from web archives'
          branch: 'twcArchives'
          create_branch: true
          # Use --force-with-lease to safely handle conflicts from a scheduled job.
          push_options: '--force-with-lease'
